</mkconfig

TARG=\
	post.html\
	index.txt\
	wmclient.dis\
	tkclient.dis\
	myclient.dis\
	titlebar.dis\

DISBIN=dis

<$ROOT/mkfiles/mkdis

all:V: $TARG

post.html: text
	man2html $prereq > $target

index.txt: text
	man -f $prereq > $target

