#!/dis/sh -n

header := {
pctl newpgrp
run /usr/caerwyn/limbo/squeak/tklib
newwidget button
}

$header &

#default config
sleep 1
echo -n .s configure -text {press me} -command {send but press} > /chan/tk.$apid
echo /chan/tk.$apid
